/* UPDATING JOURNEY ENTRY DE WITH NEW REDEEMED MEMBERS */
/* ANYONE IN THE REDEMPTION LOG DE HAS ALREADY REDEEMED (CLAIMED DISCOUNT = TRUE) */

SELECT          JOURNEY.MemberID,
			    /* FIELD USED TO REPRESENT IF MEMBER HAS CLAIMED DISCOUNT OR NOT */
                1 AS HasClaimedDiscount
FROM            [1Y_Membership_Anniversary_JourneyEntry] JOURNEY

INNER JOIN      [Redemption_Log_DE] REDEEM
ON              JOURNEY.MemberID = REDEEM.MemberID